### ISSUE TITLE
App Crashes when starting

### ISSUE THREAD

**Issue by IAbuElRuzz** [apigee/usergrid-sample-ios-messagee#1]
After adding RestKit to iOS-messagee App(I followed the exact instructions of adding RestKit),I build and run, the app but it crashes immediately with "[__NSCFConstantString path]: unrecognized selector sent to instance 0xc521c'"

**Comment by rodsimpson** [comment]
@IAbuElRuzz I know this response is very late indeed, but I am in the process of checking in a complete rebuild of Messagee.  I also experienced issues getting RestKit to work out of the box.  I was able to get it to run eventually, after following this install guide:

https://github.com/RestKit/RestKit/wiki/Installing-RestKit-v0.20.x-as-a-Git-Submodule

My new version does not have a dependency on RestKit and also properly uses our iOS SDK.
